### ISSUE TITLE
Polluted Docker Image?

### ISSUE THREAD

**Issue by FogoVoar** [Dullage/eyelign#15]
I don't know what's wrong with your Docker file, but running "build" on it takes so long that it's still running as I type this issue 15 minutes later.
Let me ask, is it really necessary to use Docker?
It's a barrier that I, a Windows user, had to sweat to try to get through (and, as I said, I still haven't been able to).
So I suggest, if possible, consider making available an alternative to Docker. 

Anyway, the purpose of the tool seems to be exactly what I'm looking for, and I hope I can test it out.

**Comment by FogoVoar** [comment]
It took 1 hour and a few more minutes but finally finished.
So if you, like me, are stuck on Docker build or "Installing dependencies from Pipfile.lock", be aware that this is normal, I guess.

**Comment by dullage** [comment]
It can indeed take a while to build. On my laptop it takes around 15 minutes.

The reason for the Docker container is to save the user from having to install the myriad of dependencies needed. I'm not even sure if you could even install all the dependencies in a Windows environment.

What I _can_ do to help is to publish an (already built) image on Docker Hub. I'll add this to my to-do this.

**Comment by dullage** [comment]
A Docker Hub image is now available.
