### ISSUE TITLE
Run the Docker image with the 2 folders as volume mounts:

### ISSUE THREAD

**Issue by ghost** [Dullage/eyelign#19]
Hi, i'm wondering how to do the 'Run the Docker image with the 2 folders as volume mounts:'. I'm not really familiar with Docker and i'm using Docker Desktop on Windows right now. But this script, man i've been looking for something like this for years so i MUST get it to work! I've been trying for some hours now and doing research, so in the mean time i though i'd just ask here also!

**Comment by dullage** [comment]
Hi @KoenJonguh, if you have Docker installed and running then in theory all you should need to do is run the example `docker run` command and just replace a couple of paths. Here's the example command:

_Note: The example in the README is spilt across multiple lines but I've joined them together here to make them Windows friendly._

```bash
docker run -it --rm -v "/input/folder/path:/input" -v "/output/folder/path:/output" dullage/eyelign:latest
```

With Docker volume mounts you have 2 paths separated by a colon. The path on the left of the colon is outside the container on your host machine. The path on the right of the colon is inside the container. Leave the ones on the right of the colon (as they are as that's where the container expects to find the folders) but change the ones on the left.

I hope this helps.

**Comment by ghost** [comment]
Okay, i will try and learn some more about Docker, thanks a lot!
